import type { FileInput, GraphEdge, GraphNode } from "./types.ts";
import { BUILD_FILES, BUILD_SUFFIXES, GOVERNANCE_FILES, CONTRACT_SUFFIXES, SOURCE_SUFFIXES, language } from "./inventory.ts";

const FILE_LEVEL_TYPES = new Set([
  "python_module","test_module","javascript_module","shell_module","go_module","go_package","rust_module",
  "ruby_module","php_module","native_module","jvm_module","dotnet_module","lua_module","elixir_module",
  "swift_module","software_package","contract_source","manifest","ci_workflow","docker","migration",
  "source_file","test_file","documentation","configuration",
]);

const GENERATED_PARTS = new Set(["gen","generated","autogen","autogenerated"]);
const VENDORED_PARTS = new Set(["third_party","third-party","vendor","vendored","external"]);

function base(path:string){return path.split("/").pop()??path;}
function ext(path:string){const b=base(path);const i=b.lastIndexOf(".");return i>=0?b.slice(i).toLowerCase():"";}
function parent(path:string){const i=path.lastIndexOf("/");return i>=0?path.slice(0,i):".";}
function depth(path:string){return path==="."?0:path.split("/").length;}

function buildSystem(path:string):string{
  const name=base(path), suffix=ext(path);
  if(name===".gn"||name==="BUILD.gn"||suffix===".gni") return "gn";
  if(["BUILD","BUILD.bazel","WORKSPACE","WORKSPACE.bazel","MODULE.bazel"].includes(name)||[".bazel",".bzl"].includes(suffix)) return "bazel";
  if(name==="CMakeLists.txt"||suffix===".cmake") return "cmake";
  if(["Makefile","GNUmakefile"].includes(name)) return "make";
  if(["meson.build","meson_options.txt"].includes(name)) return "meson";
  if(["SConstruct","SConscript"].includes(name)) return "scons";
  if(name==="pom.xml") return "maven";
  if(["build.gradle","build.gradle.kts","settings.gradle","settings.gradle.kts"].includes(name)||suffix===".gradle") return "gradle";
  if([".csproj",".fsproj",".vbproj"].includes(suffix)) return "msbuild";
  if(["Cargo.toml","Cargo.lock"].includes(name)) return "cargo";
  if(["go.mod","go.sum"].includes(name)) return "go";
  if(["package.json","package-lock.json"].includes(name)) return "npm";
  if(["pyproject.toml","requirements.txt"].includes(name)) return "python";
  if(name==="Package.swift") return "swiftpm";
  if(name==="DEPS") return "chromium-deps";
  return "other";
}

function governanceKind(path:string){
  const name=base(path);
  if(["OWNERS","CODEOWNERS"].includes(name)) return "ownership";
  if(name==="PRESUBMIT.py") return "process";
  if(name==="SECURITY.md") return "security";
  return "governance";
}

function provenance(file:FileInput):[string,string]{
  const parts=new Set(file.path.split("/").map((x)=>x.toLowerCase()));
  if([...parts].some((p)=>GENERATED_PARTS.has(p))) return ["generated","path"];
  const prefix=file.content.slice(0,4096).toLowerCase();
  if(["generated file","automatically generated","auto-generated","autogenerated","do not edit","@generated"].some((m)=>prefix.includes(m))) return ["generated","header"];
  if([...parts].some((p)=>VENDORED_PARTS.has(p))) return ["vendored","path"];
  return ["authored","repository"];
}

function nearestSubsystem(source:string, paths:Set<string>){
  const candidates=["."];
  const parts=parent(source)==="."?[]:parent(source).split("/");
  for(let i=1;i<=parts.length;i++) candidates.push(parts.slice(0,i).join("/"));
  return candidates.filter((c)=>paths.has(c)).sort((a,b)=>depth(b)-depth(a))[0]??".";
}

function resolveBuildRef(buildPath:string, raw:string, fileSet:Set<string>):string|undefined{
  const v=raw.trim();
  if(!v||v.replace(/^\/\//,"").includes(":")) return;
  let candidate:string;
  if(v.startsWith("//")) candidate=v.slice(2);
  else {
    const p=parent(buildPath);
    candidate=[...(p==="."?[]:p.split("/")), ...v.split("/")].reduce<string[]>((acc,part)=>{
      if(!part||part===".") return acc;
      if(part==="..") acc.pop(); else acc.push(part);
      return acc;
    },[]).join("/");
  }
  if(!fileSet.has(candidate)) return;
  if(SOURCE_SUFFIXES.has(ext(candidate))||CONTRACT_SUFFIXES.has(ext(candidate))) return candidate;
}

export function collectArchitectureTopology(files:FileInput[], existingNodes:GraphNode[]){
  const fileMap=new Map(files.map((f)=>[f.path,f]));
  const buildFiles=files.filter((f)=>BUILD_FILES.has(base(f.path))||BUILD_SUFFIXES.has(ext(f.path)));
  const governanceFiles=files.filter((f)=>GOVERNANCE_FILES.has(base(f.path)));
  const controls=[...buildFiles,...governanceFiles].map((f)=>f.path);
  const fileLevel=existingNodes.filter((n)=>FILE_LEVEL_TYPES.has(n.type)&&n.source);
  const sources=[...new Set(fileLevel.map((n)=>n.source))].sort();
  const subsystemPaths=new Set<string>(["."]);
  for(const source of sources){
    const parts=source.split("/");
    if(parts.length>1) subsystemPaths.add(parts[0]);
  }
  for(const control of controls){
    let p=parent(control);
    while(p){subsystemPaths.add(p); if(p===".") break; p=parent(p);}
  }

  const nodes:GraphNode[]=[];
  const edges:GraphEdge[]=[];
  const annotations=new Map<string,Record<string,string>>();
  const representative=(sub:string)=>{
    const exact=controls.filter((c)=>parent(c)===sub).sort();
    if(exact[0]) return exact[0];
    const prefix=sub==="."?"":sub+"/";
    return sources.filter((s)=>sub==="."||s.startsWith(prefix)).sort()[0]??controls.sort()[0]??sources[0]??".";
  };

  for(const sub of [...subsystemPaths].sort((a,b)=>depth(a)-depth(b)||a.localeCompare(b))){
    const rep=representative(sub);
    nodes.push({id:`subsystem:${sub}`,type:"subsystem",source:rep,layer:"generated",path:sub});
    if(sub!=="."){
      const p=parent(sub);
      edges.push({from:`subsystem:${sub}`,to:`subsystem:${p}`,type:"member_of_subsystem",evidence:rep,layer:"generated"});
    }
  }

  const directLanguages=new Map<string,Set<string>>();
  const directMembers=new Map<string,number>();
  const provCount=new Map<string,number>();
  for(const node of fileLevel){
    const sub=nearestSubsystem(node.source,subsystemPaths);
    const file=fileMap.get(node.source);
    const [prov,basis]=file?provenance(file):["authored","repository"];
    annotations.set(node.id,{source_provenance:prov,source_provenance_basis:basis,subsystem:sub});
    edges.push({from:node.id,to:`subsystem:${sub}`,type:"member_of_subsystem",evidence:node.source,layer:"generated"});
    directMembers.set(sub,(directMembers.get(sub)??0)+1);
    provCount.set(prov,(provCount.get(prov)??0)+1);
    const lang=language(node.source);
    if(SOURCE_SUFFIXES.has(ext(node.source))&&lang!=="other"){
      const set=directLanguages.get(sub)??new Set<string>(); set.add(lang); directLanguages.set(sub,set);
    }
  }

  const sourceNodes=new Map<string,string[]>();
  for(const n of fileLevel){const arr=sourceNodes.get(n.source)??[];arr.push(n.id);sourceNodes.set(n.source,arr);}
  const fileSet=new Set(files.map((f)=>f.path));
  let buildInputEdgeCount=0;
  for(const file of buildFiles){
    const sub=nearestSubsystem(file.path,subsystemPaths);
    const id=`build:${file.path}`;
    nodes.push({id,type:"build_definition",source:file.path,layer:"generated",build_system:buildSystem(file.path)});
    edges.push({from:id,to:`subsystem:${sub}`,type:"governs_build_of",evidence:file.path,layer:"generated"});
    const seen=new Set<string>();
    for(const match of file.content.matchAll(/["']([^"']+)["']/g)){
      const target=resolveBuildRef(file.path,match[1],fileSet);
      if(!target) continue;
      for(const targetId of sourceNodes.get(target)??[]){
        const key=target+"|"+targetId; if(seen.has(key)) continue; seen.add(key);
        edges.push({from:id,to:targetId,type:"declares_build_input",evidence:file.path,layer:"generated"});
        buildInputEdgeCount++;
      }
    }
  }

  for(const file of governanceFiles){
    const sub=nearestSubsystem(file.path,subsystemPaths);
    const id=`governance:${file.path}`;
    nodes.push({id,type:"governance_boundary",source:file.path,layer:"generated",governance_kind:governanceKind(file.path)});
    edges.push({from:id,to:`subsystem:${sub}`,type:"governs_boundary_of",evidence:file.path,layer:"generated"});
  }

  const aggregate=new Map<string,Set<string>>();
  for(const [sub,set] of directLanguages) aggregate.set(sub,new Set(set));
  for(const sub of [...subsystemPaths].sort((a,b)=>depth(b)-depth(a))){
    if(sub===".") continue;
    const p=parent(sub), set=aggregate.get(sub)??new Set<string>();
    const pset=aggregate.get(p)??new Set<string>(); for(const l of set) pset.add(l); aggregate.set(p,pset);
  }
  const cross=[...aggregate.entries()].filter(([,s])=>s.size>1).sort(([a],[b])=>a.localeCompare(b)).map(([sub,s])=>({subsystem:sub,languages:[...s].sort()}));

  const countObj=(m:Map<string,number>)=>Object.fromEntries([...m.entries()].sort());
  const buildCounts=new Map<string,number>(); for(const f of buildFiles){const k=buildSystem(f.path);buildCounts.set(k,(buildCounts.get(k)??0)+1);}
  const govCounts=new Map<string,number>(); for(const f of governanceFiles){const k=governanceKind(f.path);govCounts.set(k,(govCounts.get(k)??0)+1);}

  return {nodes,edges,annotations,facts:{
    subsystem_count:subsystemPaths.size,
    subsystem_direct_member_counts:countObj(directMembers),
    cross_language_subsystem_count:cross.length,
    cross_language_subsystems:cross,
    build_definition_count:buildFiles.length,
    build_definition_counts_by_system:countObj(buildCounts),
    build_input_edge_count:buildInputEdgeCount,
    governance_boundary_count:governanceFiles.length,
    governance_boundary_counts_by_kind:countObj(govCounts),
    source_provenance_counts:countObj(provCount),
  }};
}
