import type { FileInput } from "./types.ts";
import { language } from "./inventory.ts";

export type RelationshipBoundary = {
  kind:string; status:"declared"|"unresolved"; source:string; line:number; language:string;
  evidence:string; reason:string; detector:string;
};

function compact(value:string){return value.trim().replace(/\s+/g," ").slice(0,240);}
function row(kind:string,status:"declared"|"unresolved",source:string,line:number,lang:string,evidence:string,reason:string,detector="source_pattern"):RelationshipBoundary{
  return {kind,status,source,line,language:lang,evidence:compact(evidence),reason,detector};
}

export function collectRelationshipBoundaries(files:FileInput[]){
  const rows:RelationshipBoundary[]=[];
  for(const file of files){
    const lang=language(file.path);
    const lines=file.content.split("\n");
    lines.forEach((text,i)=>{
      const line=i+1;
      const trimmed=text.trim();
      if(!trimmed) return;

      if(lang==="python"){
        if(/^from\s+\S+\s+import\s+\*/.test(trimmed)) rows.push(row("wildcard_import","unresolved",file.path,line,lang,text,"Wildcard membership depends on the imported module at this revision.","python_source"));
        if(/\b(?:__import__|importlib\.import_module|importlib\.util\.spec_from_file_location)\s*\(/.test(text)){
          const declared=/\b(?:__import__|importlib\.import_module|importlib\.util\.spec_from_file_location)\s*\(\s*["']/.test(text);
          rows.push(row("dynamic_load",declared?"declared":"unresolved",file.path,line,lang,text,"The dynamic import API requires runtime evaluation; a literal argument is recorded but not promoted to an edge.","python_source"));
        }
        if(/\b(?:Depends|Inject|Provide)\s*\(|\b(?:container|injector)\.(?:get|provide|resolve)\s*\(/.test(text)) rows.push(row("dependency_injection","unresolved",file.path,line,lang,text,"Container or framework resolution selects the runtime provider.","python_source"));
        if(/\.(?:include_router|include|mount)\s*\(/.test(text)) rows.push(row("route_composition","declared",file.path,line,lang,text,"Source declares route composition; the graph does not synthesize a runtime-prefixed route.","python_source"));
      }

      if(["javascript","typescript"].includes(lang)){
        if(/\b(?:import|require)\s*\(\s*(?!["'])[^)]+\)/.test(text) && !/^\s*\/\//.test(trimmed)) rows.push(row("dynamic_load","unresolved",file.path,line,"javascript",text,"The module expression is computed at runtime."));
        if(/\b(?:container|injector)\.(?:get|resolve|register)|@(?:Inject|Injectable)\b/.test(text)) rows.push(row("dependency_injection","unresolved",file.path,line,"javascript",text,"Container registration or lookup selects the runtime provider."));
        if(/\b(?:app|router|server)\.(?:use|register)\s*\(/.test(text)) rows.push(row("route_composition","declared",file.path,line,"javascript",text,"Source declares router composition; runtime prefixes are not synthesized."));
      }
      if(lang==="ruby"&&/^\s*(?:require|require_relative|load)\s+(?!["'])[^#]+/.test(text)) rows.push(row("dynamic_load","unresolved",file.path,line,lang,text,"The required path is computed at runtime."));
      if(lang==="php"&&/\b(?:include|include_once|require|require_once)\s*(?!\(?\s*(?:__DIR__\s*\.\s*)?["'])[^;]+/.test(text)) rows.push(row("dynamic_load","unresolved",file.path,line,lang,text,"The included path is computed at runtime."));
      if(["java","kotlin","scala"].includes(lang)){
        if(/\b(?:Class\.forName|ServiceLoader\.load)\s*\(/.test(text)) rows.push(row("dynamic_load","unresolved",file.path,line,"jvm",text,"Reflection or service loading selects the runtime implementation."));
        if(/^\s*import\s+(?:static\s+)?[\w.]+\.\*\s*;?/.test(text)) rows.push(row("wildcard_import","unresolved",file.path,line,"jvm",text,"Wildcard membership depends on the imported package at this revision."));
      }
      if(/(?:Code generated by|generated file|auto-generated|autogenerated|DO NOT EDIT)/i.test(text) && line<=8) rows.push(row("generated_source","declared",file.path,line,lang,text,"The source declares itself generated."));
    });

    if(base(file.path)==="package.json" && /"(?:generate|codegen)"\s*:/.test(file.content)) rows.push(row("code_generation","declared",file.path,1,"json","package scripts","The package manifest declares code generation."));
    if(/^(?:tsconfig|jsconfig).*\.json$/i.test(base(file.path)) && /"paths"\s*:/.test(file.content)) rows.push(row("build_module_mapping","declared",file.path,1,"json","compilerOptions.paths","Build configuration declares module path mappings."));
  }
  rows.sort((a,b)=>a.source.localeCompare(b.source)||a.line-b.line||a.kind.localeCompare(b.kind)||a.evidence.localeCompare(b.evidence));
  const counts:Record<string,number>={}; let unresolved=0;
  for(const r of rows){counts[r.kind]=(counts[r.kind]??0)+1;if(r.status==="unresolved") unresolved++;}
  return {relationship_boundaries:rows,relationship_boundary_count:rows.length,unresolved_relationship_boundary_count:unresolved,relationship_boundary_counts_by_kind:Object.fromEntries(Object.entries(counts).sort())};
}
function base(path:string){return path.split("/").pop()??path;}
