export const articleBodies: Record<string, string[]> = {
  'from-goals-to-execution': [
    'Conversation can support planning, interpretation, drafting, and analysis. Durable execution requires additional system properties: persistent state, explicit ownership, authority boundaries, recoverable transitions, and evidence of what occurred after a decision was made.',
    'A generated plan is not equivalent to an execution model. If the plan has no durable representation, responsibility, status, dependency structure, or controlled transition path, the system cannot reliably distinguish an idea from work that has been accepted, authorized, attempted, completed, rejected, or failed.',
    'External actions add another requirement. Understanding an instruction is not the same operation as receiving authority to execute it. A system that can interact with connected tools must model capability, permission, review, policy, and failure handling independently from language interpretation.',
    'Ajenda AI is being developed around this distinction. Missions, plans, tasks, approvals, actions, recovery behavior, and outcomes are treated as system state rather than as temporary conversational output. The architectural problem is therefore not how to make a conversation appear productive; it is how to convert intent into controlled, inspectable execution.',
  ],
  'calibrating-ai-trust': [
    'Trust in an AI-enabled system is more useful when expressed as a relationship between capability, evidence, control, and known failure conditions rather than as a general confidence claim.',
    'A model can produce correct output in one context and fail in another. System trust therefore depends on more than model quality alone. Relevant properties can include context boundaries, tool authority, data access, evaluation coverage, state handling, human review, recovery behavior, logging, and the consequences of an incorrect action.',
    'Calibration requires the system to expose enough information to distinguish what has been demonstrated from what remains uncertain. This can include explicit maturity boundaries, architecture documentation, evaluation results, approval paths, known failure modes, and evidence showing which operations are automated, supervised, or unavailable.',
    '1DevTeam applies the same principle to development evidence. Product status, research observations, architecture artifacts, and operational claims are separated according to what the available evidence supports. Confidence language does not substitute for implementation state or proof.',
  ],
  'architectural-scope-and-corrective-repair': [
    'A software change can satisfy its immediate test while remaining incomplete at the architectural level. The visible defect may occur in one file while the behavior is owned by a contract, state transition, invariant, authority boundary, or dependency that crosses several parts of the system.',
    'This creates a distinction between local proof and system-level proof. A local test can demonstrate that a targeted behavior now passes. It does not automatically demonstrate that the correct ownership layer was modified, that downstream behavior remains valid, or that the change covers the actual architectural blast radius.',
    'Corrective pull requests provide one observable consequence of incomplete scope. A later repair may correct a defect introduced by the earlier change, expose a previously latent defect, or complete a repair whose original change surface was narrower than the system behavior it affected. Those cases must be distinguished before treating a PR sequence as evidence of causality.',
    '1DevTeam\'s current R&D program studies this relationship directly in Ajenda development. The study compares reasoning scope, change scope, architectural blast radius, proof coverage, graph state, and subsequent corrective work while controlling for competing explanations such as CI maturity, model and tooling changes, codebase maturity, test coverage, PR size, and defect class.',
  ],
}
